---
- name: Configure User Shell
  hosts: all

  tasks:
  - name: packages - enable repos
    community.general.dnf_config_manager:
      name:
      - rhel-10-for-{{ ansible_facts['architecture'] }}-extensions-rpms
      state: enabled
    become: true

  - name: packages - install
    ansible.builtin.package:
      name:
      - zsh
      - htop
      - git
      state: present
    become: true

  - name: user - Set default shell
    ansible.builtin.user:
      name: "{{ ansible_facts.env['USER'] }}"
      shell: /usr/bin/zsh
    become: true

  - name: Create temporary install directory
    ansible.builtin.tempfile:
      state: directory
      suffix: install
    changed_when: false
    register: install_dir

  - name: oh-my-zsh - Determine if installed
    ansible.builtin.stat:
      path: ~/.oh-my-zsh/oh-my-zsh.sh
    register: ohmyzsh_sh_stat

  - name: oh-my-zsh - download installer
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: "{{ install_dir.path }}/ohmyzsh-install.sh"
      mode: '0700'
    when: not ohmyzsh_sh_stat.stat.exists

  - name: oh-my-zsh - install
    ansible.builtin.command:
      cmd: "{{ install_dir.path }}/ohmyzsh-install.sh --unattended --skip-chsh"
    when: not ohmyzsh_sh_stat.stat.exists

  - name: oh-my-zsh - install plugins
    ansible.builtin.git:
      repo: '{{ repo.url }}'
      dest: '.oh-my-zsh/custom/plugins/{{ repo.name }}'
      depth: 1
      update: false
    loop:
      - { name: autoupdate, url: 'https://github.com/TamCore/autoupdate-oh-my-zsh-plugins' }
      - { name: zsh-autosuggestions, url: 'https://github.com/zsh-users/zsh-autosuggestions' }
      - { name: zsh-syntax-highlighting, url: 'https://github.com/zsh-users/zsh-syntax-highlighting.git' }
    loop_control:
      loop_var: repo
      label: "{{ repo.name }}"

  - name: oh-my-zsh - install themes
    ansible.builtin.git:
      repo: '{{ repo.url }}'
      dest: '.oh-my-zsh/custom/themes/{{ repo.name }}'
      depth: 1
      update: false
    loop:
      - { name: powerlevel10k, url: 'https://github.com/romkatv/powerlevel10k.git' }
    loop_control:
      loop_var: repo
      label: "{{ repo.name }}"

  - name: oh-my-zsh - enable plugins
    ansible.builtin.lineinfile:
      path: ~/.zshrc
      regexp: '^plugins='
      line: plugins=(autoupdate git zsh-autosuggestions zsh-syntax-highlighting)

  - name: oh-my-zsh - enable theme
    ansible.builtin.lineinfile:
      path: ~/.zshrc
      regexp: '^ZSH_THEME='
      line: ZSH_THEME="powerlevel10k/powerlevel10k"

  - name: user - check if ~/.local/bin is on path
    lineinfile:
      state: absent
      path: ~/.zshrc
      regexp: '^export PATH="\$PATH:{{ ansible_facts.env.HOME }}/.local/bin"$'
    check_mode: true
    changed_when: false # This just makes things look prettier in the logs
    register: check_zsh_local_bin_path

  - name: user - add ~/.local/bin to path
    lineinfile:
      state: present
      path: ~/.zshrc
      line: 'PATH="$PATH:{{ ansible_facts.env.HOME }}/.local/bin"'
    when: check_zsh_local_bin_path.found == 0
