---
installPlanApproverAndVerifyJobsImage: registry.redhat.io/openshift4/ose-cli-rhel9@sha256:dcb3f93d34aa0fdab33eb37949adfaa8fdd11ff3479363bb7735c5ba3eb345ce

operatorGroups:
- name: cert-manager-operator
  createNamespace: true
  targetOwnNamespace: true
operators:
- channel: stable-v1
  installPlanApproval: Manual
  automaticIntermediateManualUpgrades: true
  name: openshift-cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  csv: cert-manager-operator.v1.18.1
  namespace: cert-manager-operator
