kind: Kustomization

namespace: openshift-config

resources:
- Authentication_cluster.yaml
- OAuth_cluster.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: multiplexer-proxy-webhook
  files:
  - kubeConfig=files/KubeConfig_multiplexer-proxy-webhook.yaml
