---
installPlanApproverAndVerifyJobsImage: registry.redhat.io/openshift4/ose-cli-rhel9@sha256:dcb3f93d34aa0fdab33eb37949adfaa8fdd11ff3479363bb7735c5ba3eb345ce

operatorGroups:
- name: rhbk-operator
  createNamespace: true
  targetOwnNamespace: false
  otherTargetNamespaces:
  - keycloak
operators:
- channel: stable-v26.4
  installPlanApproval: Manual
  automaticIntermediateManualUpgrades: true
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  csv: rhbk-operator.v26.4.11-opr.1
  namespace: rhbk-operator
