---
- name: IDM Server
  hosts: ipaserver
  become: true

  tasks:
  - name: ipaserver | install
    ansible.builtin.import_role:
      name: freeipa.ansible_freeipa.ipaserver
    vars:
      state: present

  - name: ipaserver | create dns records
    freeipa.ansible_freeipa.ipadnsrecord:
      name: '{{ ipadnsrecord.name }}'
      zone_name: '{{ ipaserver_domain }}'
      ip_address: '{{ ipadnsrecord.ip_address }}'
      create_reverse: '{{ ipadnsrecord.create_reverse | default(true) }}'
      ipaadmin_password: '{{ ipaadmin_password }}'
      state: present
    loop: '{{ ipadnsrecords }}'
    loop_control:
      loop_var: ipadnsrecord
      label: '{{ ipadnsrecord.name }}'
