---
- name: IDM Server
  hosts: ipaserver
  become: true

  tasks:
  - name: ipaserver | install
    ansible.builtin.import_role:
      name: freeipa.ansible_freeipa.ipaserver
    vars:
      state: present

  - name: ipaserver | create dns records
    freeipa.ansible_freeipa.ipadnsrecord:
      ipaadmin_password: '{{ ipaadmin_password }}'
      zone_name: '{{ ipaserver_domain }}'
      records: '{{ ipadnsrecords }}'
